### ISSUE TITLE
getImage function throws expectation error

### ISSUE THREAD

**Issue by JanYalda** [DantSu/php-osm-static-api#11]
# getImage function

I have a utilized the getImage function in a feature that I have on a personal project and I noticed recently it's throwing an error!

Let me know if you need anything else to debug this issue.

## Stack Trace:
```
ErrorException: imagecreatefromstring(): Data is not in a recognized format in ...\vendor\dantsu\php-image-editor\src\Image.php:245
#1 ...\vendor\dantsu\php-image-editor\src\Image.php(245): imagecreatefromstring()
#2 ...\vendor\dantsu\php-image-editor\src\Image.php(233): DantSu\PHPImageEditor\Image->data()
#3 ...\vendor\dantsu\php-image-editor\src\Image.php(332): DantSu\PHPImageEditor\Image::fromData()
#4 ...\vendor\dantsu\php-image-editor\src\Image.php(296): DantSu\PHPImageEditor\Image->curl()
#5 ...\vendor\dantsu\php-osm-static-api\src\TileLayer.php(198): DantSu\PHPImageEditor\Image::fromCurl()
#6 ...\vendor\dantsu\php-osm-static-api\src\OpenStreetMap.php(217): DantSu\OpenStreetMapStaticAPI\TileLayer->getTile()
#7 ...\vendor\dantsu\php-osm-static-api\src\OpenStreetMap.php(271): DantSu\OpenStreetMapStaticAPI\OpenStreetMap->getMapImage()
#8 ...\app\MY_FILE_CALL: DantSu\OpenStreetMapStaticAPI\OpenStreetMap->getImage()
```

**Comment by DantSu** [comment]
yes I need more info,. What are you trying to do ? PHP version ? Etc... I not read in your mind. 😉

**Comment by JanYalda** [comment]
For sure 😅 So after taking another look it seems to be the `TileLayer` url from `$tileLayer1` that I've used from this [example](https://github.com/DantSu/php-osm-static-api/blob/7319190d4e6afbad3ae9463fc4a6211ce2515d9d/src/samples/sample4.php#L20)

Can you please verify on your end if adding that TileLayer still allows the OpenStreetMap library's  `getImage` feature to work? because it's failing for me with that exception from above but removing that exact tile it then works fine.

**Comment by DantSu** [comment]
Ok that come from the tileLayer. It's seems to not working, 

Look here for raster tile layer : http://leaflet-extras.github.io/leaflet-providers/preview/index.html

**Comment by DantSu** [comment]
* many of them need an API key

**Comment by JanYalda** [comment]
Thank you for pointing me to that resource 🙏 
This had nothing to do with the library just that Tile Layer that I used seemed to stop working maybe they also switched to an API key.
I'll let you close this issue however you see fit.

Thank you for your time!

**Comment by rafalkwasniak** [comment]
Hi!

I have a similar problem.
I am using this code: (https://github.com/DantSu/php-osm-static-api/blob/master/src/samples/sample2.php)
Until August 22, 2023, the created thumbnails looked like this: (https://pobierzgpx.pl/storage/maps/202308/64e3a6636c568.png)
Now they look like this: (https://pobierzgpx.pl/storage/maps/202308/64e4d01219e5a.png)
I'm not using the TileLayer function, I'm using the default OpenStreetMap parameters.
My code waits a long time for the ->getImage() function.

Please help!

**Comment by DantSu** [comment]
update the library to the latest version.

**Comment by DantSu** [comment]
this dependence : https://github.com/DantSu/php-image-editor have to be at version 1.4.5. That will solve your problem.

**Comment by ghalysaqqal** [comment]
> this dependence : https://github.com/DantSu/php-image-editor have to be at version 1.4.5. That will solve your problem.

How can use it with osm static map, could enter an example please ?

**Comment by DantSu** [comment]
`composer update dantsu/php-osm-static-api`

if is not enought : 

`composer remove dantsu/php-osm-static-api`
`composer require dantsu/php-osm-static-api`

**Comment by ghalysaqqal** [comment]
you mean the update inside the dantsu/php-osm-static-api ?
