### ISSUE TITLE
Test server connectivity

### ISSUE THREAD

**Issue by drnickyoung** [DantSu/php-osm-static-api#12]
Hi,

A fantastic library. Got code set-up and running, downloads and saves as a JPG. Works perfect, but just testing a few scenarios. If for whatever reason the tile server is unreachable the image saves as one big black square. Which is fine, it isn't loading anything. But was wondering if there is a way to do a quick check that the tile server can be reached before building the map and saving it? 

Thanks?

**Comment by DantSu** [comment]
`failCurlOnError` on `TileServer` class. That will throw an error if a tile is not loaded. Look at the documentation.

**Comment by drnickyoung** [comment]
I have read the instructions and indeed put failCurlOnError to true. That did cause a fatal error as expected. For anyone else wanting to catch the exception, you need to ensure that whatever function calls the tiles is within your try/catch block. So as an example:

```
try {
         $latlon = new LatLng( $lat, $lon );
	 $tilelayer = new TileLayer( 'serveraddress/{z}/{x}/{y}.png', '&copy; OpenStreetMap contributors', 'abc', array(), true );
	 $osm = new OpenStreetMap( $latlon, 15, 600, 400, $tilelayer );
	 $img = $osm->getImage();
} catch ( \Exception $e ) {
	echo 'Caught exception: ',  $e->getMessage(), "\n";
}
```

And yes I know that can be simplified.
