### ISSUE TITLE
How to return image in base64?

### ISSUE THREAD

**Issue by AnderNascimento** [DantSu/php-osm-static-api#13]
I'm trying to convert the map image to base64, but I haven't had any success. Could you help me?

**Comment by DantSu** [comment]
Look here https://github.com/DantSu/php-image-editor/blob/master/docs/classes/DantSu/PHPImageEditor/Image.md ->getBase64JPG

**Comment by AnderNascimento** [comment]
Thank you bro, you're amazing.
