### ISSUE TITLE
Some issues when try to integrate your code in a Laravel project

### ISSUE THREAD

**Issue by Laxeer0** [DantSu/php-osm-static-api#16]
When I go to integrate the library into my Laravel system, it gives me an error with the schema, specifically at line 311 of the Image class.

The error is: Undefined array key "REQUEST_SCHEME"

![image](https://github.com/DantSu/php-osm-static-api/assets/30774549/82e45753-dc1b-4b35-af49-4e7ccdb944c6)

**Comment by DantSu** [comment]
Your $_REQUEST php environnement variable is not defined properly. `$_REQUEST["REQUEST_SHEME"]` is missing.

`$_REQUEST["REQUEST_SHEME"] = 'https';` somewhere in your code will solve your issue.

Is not an issue due to laravel. It's an apache/php configuration problem.

**Comment by Laxeer0** [comment]
I've been tried to set the request scheme manually, but doesn't work too. I use this code inside a livewire component. If you have discord i can show you more about this.

**Comment by DantSu** [comment]
Make sure that this 3 array keys are defined : (If they are defined before using php-osm-static-api, you will not have issue like this)
```php
$_SERVER["REQUEST_SCHEME"] = 'https';
$_SERVER["HTTP_HOST"] = 'localhost'; // can be a domain name www.example.com
$_SERVER["REQUEST_URI"] = '/'; // can be an URI more complexe like '/home/my_page?var=3
```

**Comment by Laxeer0** [comment]
I use it with OpenStreetMap, but i fix it, wrapping the method and using laravel request.
