### ISSUE TITLE
PHP code example produces tiny image

### ISSUE THREAD

**Issue by malcolmfowler** [DantSu/php-osm-static-api#17]
Hello,
When running the example code it presents a tiny image in the centre of the screen, approx 10 pixels wide.
I have tried adjusting the scaling but nothing changes.
Thanks

**Comment by DantSu** [comment]
example code ?
Share me screenshots.

**Comment by malcolmfowler** [comment]
Hello

Thank you for getting back to me so quickly. I have show the steps I followed below. 

Rgds

Malcolm

1. Created a new project and ran composer as shown. 

2. Copied the example code shown on the Github page into a new php file.

3. Ran the page in Chrome and the result is this

4. Tried running it in Firefox and get this result

**Comment by DantSu** [comment]
Don't reply by mail. Come on github.

**Comment by malcolmfowler** [comment]
Sorry Franck, moving to Github

**Comment by malcolmfowler** [comment]
Attached a word doc file with output from example code
[Results from running example code from github.docx](https://github.com/DantSu/php-osm-static-api/files/14312030/Results.from.running.example.code.from.github.docx)

**Comment by DantSu** [comment]
ok it's broken image

remove this line : `\header('Content-type: image/png');`

**Comment by malcolmfowler** [comment]
Thank you, working now, I had actually forgotten to add this line of code

`require_once("vendor/autoload.php");`

Totally my mistake, thanks for your support.
Malcolm

**Comment by DantSu** [comment]
Great !
