### ISSUE TITLE
make sure markers are same distance borders

### ISSUE THREAD

**Issue by kasperkamperman** [DantSu/php-osm-static-api#18]
![rhederlaag_840](https://github.com/DantSu/php-osm-static-api/assets/1760616/6cd5eb0b-5114-4a41-a965-470424bf9961)

I would like to "shift" the map so the marker bounds are all from the same distance from the borders. 
Right now the points seem to be used. However, it makes more sense if the "top" of the marker is used, when markers have a different anchor point: 

```$marker->setAnchor(Markers::ANCHOR_CENTER, Markers::ANCHOR_BOTTOM);```

**Comment by DantSu** [comment]
You can do this by padding the map + cropping the final image before save it.

**Comment by kasperkamperman** [comment]
How would I do this? I add padding to the markers with fitToMarkers? 
Then how do I decide the crop position? (I suppose cropping happens with php image manipulation and not with this libary). 

If you can point me to functions I could use, that would be helpful solving this problem. 

Thanks in advance for helping out.

**Comment by DantSu** [comment]
```php
    $WIDTH_MAP = $DESIRED_WIDTH_MAP +$HEIGH_OF_YOUR_MARKER * 2;
    $HEIGHT_MAP = $DESIRED_HEIGHT_MAP + $HEIGH_OF_YOUR_MARKER;
```

`->fitToMarkers($HEIGH_OF_YOUR_MARKER)`

```php
    ->getImage()
    ->crop($WIDTH_MAP - $HEIGH_OF_YOUR_MARKER * 2, $HEIGHT_MAP - $HEIGH_OF_YOUR_MARKER, $HEIGH_OF_YOUR_MARKER, $HEIGH_OF_YOUR_MARKER)
    ->displayPNG();
```

**Comment by kasperkamperman** [comment]
``` 
$WIDTH_MAP = $DESIRED_WIDTH_MAP +$WIDTH_OF_YOUR_MARKER * 2;
$HEIGHT_MAP = $DESIRED_HEIGHT_MAP + $HEIGHT_OF_YOUR_MARKER;
->fitToMarkers($HEIGHT_OF_YOUR_MARKER)
```
```
->getImage()
->crop($WIDTH_MAP - $WIDTH_OF_YOUR_MARKER * 2, $HEIGHT_MAP - $HEIGHT_OF_YOUR_MARKER, $WIDTH_OF_YOUR_MARKER, $HEIGHT_OF_YOUR_MARKER)
->displayPNG();
```

Thanks, modified the pseudo code a bit for future reference. 
I did cropping with ImageMagick.

**Comment by DantSu** [comment]
`->getImage()` return an instance of https://github.com/DantSu/php-image-editor . You have croping , resize and more... methods available.

I did a mistake : 
`->crop($WIDTH_MAP - $WIDTH_OF_YOUR_MARKER * 2, $HEIGHT_MAP - $HEIGHT_OF_YOUR_MARKER, $WIDTH_OF_YOUR_MARKER, 0)`
it's 0 the last param.

**Comment by DantSu** [comment]
And I think you want to did this : 

`->crop($WIDTH_MAP - $HEIGHT_OF_YOUR_MARKER  * 2 + $WIDTH_OF_YOUR_MARKER + 30, $HEIGHT_MAP - $HEIGHT_OF_YOUR_MARKER, $WIDTH_OF_YOUR_MARKER, 0)`

because the padding is $HEIGHT_OF_YOUR_MARKER but you want to keep half of the width of your marker + 15px on each side.
