### ISSUE TITLE
default zoomlevel, fittomarkers zoom out

### ISSUE THREAD

**Issue by kasperkamperman** [DantSu/php-osm-static-api#19]
I'm using fit to markers, to make sure all the markers fit on the map. 
However, the function zoom as much in (higher number) so markers fit in the image. 

I would like to have a preferred zoomlevel and if the markers don't fit in, then to zoom out (but not the other way round). 

Is there a way to accomplish this?

**Comment by DantSu** [comment]
Not possible.
