### ISSUE TITLE
Change the tag of this project to #OpenStreetMap instead of #openstreetmapS

### ISSUE THREAD

**Issue by thibaultmol** [DantSu/php-osm-static-api#20]
Hi,
This is a very small thing, but I noticed your github project has the # openstreetmaps (with an S at the end, but it should actually be openstreetmap without the S), it's an easy typo to make.

**Comment by DantSu** [comment]
Github suggest me openstreetmap and openstreetmaps, I have add both. Tags on github are commonly lower case.

I don't know if we talking about the same thing ^^

**Comment by thibaultmol** [comment]
Sorry yeah, I know they're lowercase, I was mainly intending to put the S in capitals so that the it was more obvious what I was pointing to. 
Hadn't noticed you also had the correct tag on your repo, fair enough then
