### ISSUE TITLE
Draw circle on map

### ISSUE THREAD

**Issue by virtualize** [DantSu/php-osm-static-api#6]
Would it be possible to draw a circle on the map, like in this example:

![Screenshot 2022-05-17 at 18 10 05](https://user-images.githubusercontent.com/220102/168859463-5e74ab92-394d-4b4e-af5f-336e5cb15c6e.png)

I saw that your Image class in php-image-editor has a drawCircle method, but I'm not sure how to use it to draw on a map image.
Thanks for any pointers.

**Comment by DantSu** [comment]
I wiil look to this tomorrow.

**Comment by DantSu** [comment]
use v0.3.0. 

Look here : https://github.com/DantSu/php-osm-static-api/blob/master/src/samples/sample3.php

**Comment by virtualize** [comment]
Wow. Impressive. Thanks a lot! Will test it ASAP.

**Comment by virtualize** [comment]
@DantSu I've testet it and works really nice. Thank you very much.
