### ISSUE TITLE
I'm able to draw shapes but base map doesn't show!

### ISSUE THREAD

**Issue by JanYalda** [DantSu/php-osm-static-api#8]
Initially when I first used this package it worked just fine with any coordinates, but I had to update my php version to 8 to accommodate other needs of my project and I'm not sure if that has anything to do with this but it now has stopped working like before mainly that the base map(`tileServer?`) doesn't show up anymore but the drawing of the spatial shapes still functions and the display/save options work as well!

Here's how it looks:
![test](https://user-images.githubusercontent.com/22034025/174924975-46b555f4-8fda-4486-8b84-21cab2ee8c67.png)

**Comment by DantSu** [comment]
If you do this in a php file, what do you see ?

```php
        $curl = curl_init();
        curl_setopt($curl, CURLOPT_URL, 'https://tile.openstreetmap.org/16/33235/23740.png');
        curl_setopt($curl, CURLOPT_USERAGENT, 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:91.0) Gecko/20100101 Firefox/91.0');
        curl_setopt($curl, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($curl, CURLOPT_TIMEOUT, 5);
        $image = curl_exec($curl);
        curl_close($curl);

        \header('Content-type: image/png');
        echo $image;
```

**Comment by JanYalda** [comment]
@DantSu It didn't work at first, but it worked after adding the following curl transfer option:
`curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, false);`

**Comment by DantSu** [comment]
Ok the problem seems to come from your php or network configuration. Maybe curl need a ssl extension to works.

**Comment by DantSu** [comment]
In my php.ini : 

```
[curl]
; A default value for the CURLOPT_CAINFO option. This is required to be an
; absolute path.
;curl.cainfo =
curl.cainfo = "C:\laragon\etc\ssl\cacert.pem"
```

**Comment by JanYalda** [comment]
@DantSu Yes, that was exactly it I had the cert already which makes sense why it was working before the update but after the update of `php` I updated/added just the extensions that I knew I needed and I missed this. 

Thank you so much for your time and the help!
